import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("imu_log.csv")
print(data.head())
print(data.describe())
plt.plot(data["time_s"], data["accel_x"], label ="Accel X")
plt.plot(data["time_s"], data["accel_y"], label ="Accel Y")
plt.plot(data["time_s"], data["accel_z"], label ="Accel Z")
plt.xlabel("Time (s)")
plt.ylabel("Acceleration (g)")
plt.title("MPU-6050 Acceleration vs Time")
plt.legend()
plt.grid(True)
plt.savefig("acceleration_plot.png", dpi=300, bbox_inches="tight")
plt.show()
plt.figure()
plt.plot(data["time_s"], data["gyro_x"], label="Gyro X")
plt.plot(data["time_s"], data["gyro_y"], label="Gyro Y")
plt.plot(data["time_s"], data["gyro_z"], label="Gyro Z")
plt.xlabel("Time (s)")
plt.ylabel("Angular Rate (deg/s)")
plt.title("MPU-6050 Gyroscope vs Time")
plt.legend()
plt.grid(True)
plt.savefig("gyroscope_plot.png", dpi=300, bbox_inches="tight")
plt.show()
